version: '3'

volumes:
  certbotdata:

networks:
  backend-network:
    driver: bridge

services:
  nginx:
    image: nginx:alpine-slim
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./letsencrypt:/etc/letsencrypt
      - certbotdata:/var/www/certbot
    networks:
      - backend-network
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - certbotdata:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  planetiler:
    image: ghcr.io/onthegomap/planetiler:latest
    volumes:
      - './tileserver:/output'
    command: --force --download --osm_url=https://download.geofabrik.de/europe/portugal-latest.osm.pbf --fetch-wikidata --free_osm_after_read

  tileserver:
    image: maptiler/tileserver-gl
    restart: unless-stopped
    volumes:
      - './tileserver:/data'
    networks:
      - backend-network
